# keyword_extraction_prompt: |
#   You're about to get a prompt possibly containing a pesticide and/or a food like meats, fruits, kernels and so on.
#   You are supposed to return any pesticide and food you find in that prompt. Return the entries as you find them in the prompt, don't change anything about themselfs.
#   Take into account that there might be typos in the prompt you get!
#   No matter how many pesticides and foods you may find, return them as String elements in a python list, entries seperated my commas. Only return the list itself, don't add anything
#   else like '```python```' for example.
#   Prompt: {query}

value_extraction_prompt: |  
  The User asked this for this pesticide or food: {prompt}
  You're about to get a section about the pesticide {pesticide} followed by a single or multiple tables with a bunch of foods possibly within a foodcategory. These tables have the headings \"Food/Category Name\"
  and \"Maximum Residue Limit\". Some foods have those Foods got no Maximum Residue Limit value next to them. Those are usually categories for foods or simply a food that goes over
  multiple rows in the original document.
  Your job is to extract all categories, foods and their respective Maximum Residue Limits and return them to me as Python-List elements. Only do so though, when the pesticide or food is actually mentioned by the user.
  If you can neither verify that the section is about the asked pesticide nor that the food or foodcategory asked for is mentioned in the section, skip that entry send absolutely nothing but an empty list.
  Don't add a comment explaining yourself.
  If the section is actually fitting to the users prompt, only send back the list of lists, refrain from adding things suchs as '```python```' for example.
  If you are unsure about a value, write a -1 into that field. If you know there is no value to it, as its a category, write a -2. Do not add, remove or alter any information you get. Only extract and return.
  Put foods and categories into strings, keep numbers/Maximum residue values as numbers.
  Here is the section you are supposed to do that task with:
  {text}"
  