upsert_chinese_query: |
  INSERT INTO chinese_pesticide_residues (pesticide, text, version)
  VALUES %s
  ON CONFLICT (pesticide)
  DO UPDATE SET
    text = EXCLUDED.text,
    version = EXCLUDED.version
  WHERE chinese_pesticide_residues.version < EXCLUDED.version;

insert_eu_query: |
  INSERT INTO european_pesticide_residues (pesticide, product, mrl, applicability, application_date)
  VALUES %s

fuzzy_single_query: |
  SELECT DISTINCT t.pesticide, t.text 
  FROM chinese_pesticide_residues AS t,
    regexp_split_to_table(t.text, '\s+') AS word
  WHERE similarity(word, %s) > 0.80;
  
multiple_query: |
  SELECT DISTINCT t.pesticide, t.text
  FROM chinese_pesticide_residues AS t
  WHERE t.text ILIKE %s;
  
get_unique_pesticides_eu: |
  SELECT DISTINCT t.pesticide
  FROM european_pesticide_residues AS t;

get_relevant_applicable_entries_eu: |
  SELECT DISTINCT t.pesticide, t.product, t.mrl, t.applicability
  FROM european_pesticide_residues AS t
  WHERE t.pesticide ~ %s and t.applicability ~ 'Applicable';
  