upsert_chinese_query: |
  INSERT INTO chinese_pesticide_residues (pesticide, text, version)
  VALUES %s
  ON CONFLICT (pesticide)
  DO UPDATE SET
    text = EXCLUDED.text,
    version = EXCLUDED.version
  WHERE chinese_pesticide_residues.version < EXCLUDED.version;

insert_eu_query: |
  INSERT INTO european_pesticide_residues (pesticide, product, mrl, applicability, application_date)
  VALUES %s

# does reset the sequence for the id's aswell, might need adaptation depending on how id's are being generated!
truncate_eu_query: |
  TRUNCATE TABLE european_pesticide_residues RESTART IDENTITY;

get_fitting_chinese_chunks_query: |
  SELECT DISTINCT t.pesticide, t.text
  FROM chinese_pesticide_residues AS t
  WHERE t.text ILIKE %s;
  
get_unique_pesticides_eu: |
  SELECT DISTINCT t.pesticide
  FROM european_pesticide_residues AS t;

# don't add DISTINCT here! 1. we lose some entries we need, 
# 2. PostgreSQL sorts when removing entries with DISTINCT, that makes categories obsolete and adulterates data
get_relevant_applicable_entries_eu: |
  SELECT t.pesticide, t.product, t.mrl
  FROM european_pesticide_residues AS t
  WHERE t.pesticide = %s and t.applicability = 'Applicable';
